export const THEME = {
  MAIN_COLOR: "#116062",
  FONT_COLOR: "#fff",
  RED_COLOR_BUTTON: "#CC0000",
  BLUE_COLOR_BUTTON: "#3949ab",
  DRAWER_COLOR: "#c6cbef",
  TAB_COLOR_FAVARITE: "#483D8B",
  TAB_COLOR_NOTES: "#DAA520",
};
